{"version":1,"defects":{"Tests\\Unit\\RouterTest::test_that_there_are_no_routes_when_router_is_created":8,"Tests\\Unit\\RouterTest::test_that_it_throws_not_found_exception":8,"Tests\\Unit\\RouterTest::test_that_it_resolves_route_from_a_closure":7},"times":{"Tests\\Unit\\RouterTest::test_it_can_register_a_route":0.001,"Tests\\Unit\\RouterTest::test_that_it_can_register_a_route":0.001,"Tests\\Unit\\RouterTest::test_that_it_registers_a_get_route":0.001,"Tests\\Unit\\RouterTest::test_that_it_registers_a_post_route":0.001,"Tests\\Unit\\RouterTest::test_that_there_are_no_routes_when_router_is_created":0.001,"Tests\\Unit\\RouterTest::test_that_it_throws_not_found_exception":0.005,"Tests\\Unit\\RouterTest::test_that_it_throws_not_found_exception with data set #0":0.001,"Tests\\Unit\\RouterTest::test_that_it_throws_not_found_exception with data set #1":0.001,"Tests\\Unit\\RouterTest::test_that_it_throws_not_found_exception with data set #2":0.001,"Tests\\Unit\\RouterTest::test_that_it_throws_not_found_exception with data set #3":0.001,"Tests\\Unit\\RouterTest::test_that_it_resolves_route_from_a_closure":0.001,"Tests\\Unit\\RouterTest::test_that_it_resolves_route":0.001}}